version: '3.6'
services:
  backend:
    build:
      context: ./backend-minitable
      target:  backendApp
    image: tkachenkovitaliy/minitable-backend
    restart: always
    container_name: backend
    ports:
      - 8081:8081

  frontend:
    build: ./frontend-minitable
    image: tkachenkovitaliy/minitable-frontend
    restart: always
    container_name: frontend
    ports:
      - 8080:8080
    depends_on:
      - backend

